# Generated by Django 5.1.12 on 2025-09-14 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ф.И.О.')),
                ('growth', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Biochemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('alat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('asat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('ldh', models.DecimalField(decimal_places=7, max_digits=10)),
                ('cpk', models.DecimalField(decimal_places=7, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=200)),
                ('regime', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=1000, verbose_name='Жалобы')),
                ('anamnesis', models.CharField(max_length=1000, verbose_name='Анамнез')),
                ('diet', models.CharField(choices=[('MEAT', 'преимущественно мясной'), ('PLANT', 'преимущественно растительный'), ('VEG', 'вегатарианский'), ('LOWCARB', 'низкоуглеводный'), ('KET', 'кетогенный'), ('RAW', 'сыроедение'), ('OTHER', 'другое')], max_length=7)),
                ('mealscount', models.IntegerField()),
                ('snacks', models.CharField(choices=[('N', 'нет'), ('R', 'редко'), ('O', 'несколько раз в день')], max_length=1)),
                ('preference', models.CharField(choices=[('MEAT', 'мясо'), ('FISH', 'руба'), ('DAIR', 'молочные продукты'), ('EGGS', 'яйца'), ('VEGS', 'овощи'), ('FRUT', 'фрукты'), ('GROA', 'крупы'), ('SWET', 'сладкое'), ('FAST', 'фаст-фуд'), ('COFE', 'напитки с кофе'), ('ALCO', 'алкоголь')], max_length=4)),
                ('cardiovascular', models.CharField(choices=[('Y', 'да'), ('N', 'нет'), ('U', 'неизвестно')], max_length=1)),
                ('oncological', models.CharField(choices=[('Y', 'да'), ('N', 'нет'), ('U', 'неизвестно')], max_length=1)),
                ('diabetes', models.CharField(choices=[('Y', 'да'), ('N', 'нет'), ('U', 'неизвестно')], max_length=1)),
                ('thyroid', models.CharField(choices=[('Y', 'да'), ('N', 'нет'), ('U', 'неизвестно')], max_length=1)),
                ('autoimmune', models.CharField(choices=[('Y', 'да'), ('N', 'нет'), ('U', 'неизвестно')], max_length=1)),
                ('allergic', models.CharField(choices=[('Y', 'да'), ('N', 'нет'), ('U', 'неизвестно')], max_length=1)),
                ('foodAllergy', models.CharField(max_length=150, verbose_name='Пищевая аллергия')),
                ('medicineAllergy', models.CharField(max_length=150, verbose_name='Медикаментозная аллергия')),
                ('seasonalAllergy', models.CharField(max_length=150, verbose_name='Сезонная аллергия')),
                ('contactAllergy', models.CharField(max_length=150, verbose_name='Контактная аллергия')),
                ('noAllergy', models.CharField(max_length=150, verbose_name='Отсутствие аллергии')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('biochemistry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.biochemistry')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.prescription')),
            ],
        ),
    ]
