# Generated by Django 5.1.12 on 2025-09-21 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='prescription',
        ),
    ]
