# Generated by Django 5.1.12 on 2025-10-25 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_report_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='carbohydratemetabolism',
            name='fastingGlucose',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Глюкоза (натощак)'),
        ),
        migrations.AlterField(
            model_name='micronutrients',
            name='sodium',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Натрий'),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='form.patient')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.questionnairetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='form.questionnairetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('scale', models.CharField(default='0148', max_length=16)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.sectiontemplate')),
            ],
            options={
                'unique_together': {('section', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form.questionnaire')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.questiontemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['questionnaire'], name='form_answer_questio_2f09a7_idx'), models.Index(fields=['question'], name='form_answer_questio_3e9a26_idx')],
                'unique_together': {('questionnaire', 'question')},
            },
        ),
    ]
