# Generated by Django 5.1.12 on 2025-10-26 01:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_questionnairetemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
