# Generated by Django 5.1.12 on 2025-11-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_questionnaire_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontemplate',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectiontemplate',
            name='height',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectiontemplate',
            name='low',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
