# Generated by Django 5.1.12 on 2025-11-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_sectiontemplate_description_sectiontemplate_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LymphInspectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Опция осмотра лимфоузлов',
                'verbose_name_plural': 'Опции осмотра лимфоузлов',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='insp_lymph',
            field=models.ManyToManyField(blank=True, help_text='Можно выбрать несколько состояний', related_name='reports', to='form.lymphinspectoption'),
        ),
    ]
