# Generated by Django 5.1.12 on 2025-11-22 23:22

from django.db import migrations


INSP_LYMP_THYR = {
    "NRM": "не увеличены",
    "PAL": "пальпируются",
    "PNF": "болезненны",
    "PNL": "безболезненны",
    "NON": "-",   
}

def forwards_func(apps, schema_editor):
    LymphInspectOption = apps.get_model("form", "LymphInspectOption")
    Report = apps.get_model("form", "Report")

    code_to_obj = {}
    for code, label in INSP_LYMP_THYR.items():
        obj, created = LymphInspectOption.objects.get_or_create(
            code=code,
            defaults={"label": label},
        )
        # если label в будущем поменяешь, можно обновлять:
        if not created and obj.label != label:
            obj.label = label
            obj.save(update_fields=["label"])
        code_to_obj[code] = obj

    # 2. переносим данные из старого CharField в M2M
    for report in Report.objects.all():
        code = report.insp_Lymph
        if not code:
            continue

        # если хочешь НЕ переносить "NON" (т.е. считать его «нет отмеченных состояний»),
        # раскомментируй:
        if code == "NON":
            continue

        opt = code_to_obj.get(code)
        if opt is not None:
            report.insp_lymph.add(opt)


def backwards_func(apps, schema_editor):
    """
    Обратная миграция: если откатываемся, берём первый элемент из M2M
    и кладём в старое поле insp_Lymph.
    """
    LymphInspectOption = apps.get_model("clinic", "LymphInspectOption")
    Report = apps.get_model("clinic", "Report")

    for report in Report.objects.all():
        opts = list(report.insp_lymph.all())
        if opts:
            # берём первый попавшийся код
            report.insp_Lymph = opts[0].code
        else:
            report.insp_Lymph = "NON"
        report.save(update_fields=["insp_Lymph"])


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0006_lymphinspectoption_report_insp_lymph"),  
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
