# Generated by Django 5.1.12 on 2025-11-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_migrate_insp_lymph_to_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscoskeletalInspectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Опция осмотра опорно‑двигательного аппарата',
                'verbose_name_plural': 'Опции осмотра опорно‑двигательного аппарата',
            },
        ),
        migrations.CreateModel(
            name='SkinInspectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Опция осмотра кожи и слизистых',
                'verbose_name_plural': 'Опции осмотра кожи и слизистых',
            },
        ),
        migrations.CreateModel(
            name='ThyroidInspectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Опция осмотра щитовидной железы',
                'verbose_name_plural': 'Опции осмотра щитовидной железы',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='insp_lymph',
            field=models.ManyToManyField(blank=True, help_text='Можно выбрать несколько состояний', related_name='reports', to='form.lymphinspectoption', verbose_name='Лимфатические узлы'),
        ),
        migrations.AddField(
            model_name='report',
            name='insp_musculoskeletal',
            field=models.ManyToManyField(blank=True, help_text='Можно выбрать несколько состояний', related_name='reports', to='form.muscoskeletalinspectoption', verbose_name='Опорно‑двигательный аппарат'),
        ),
        migrations.AddField(
            model_name='report',
            name='insp_skin',
            field=models.ManyToManyField(blank=True, help_text='Можно выбрать несколько состояний', related_name='reports', to='form.skininspectoption', verbose_name='Кожа и слизистые'),
        ),
        migrations.AddField(
            model_name='report',
            name='insp_thyroid',
            field=models.ManyToManyField(blank=True, help_text='Можно выбрать несколько состояний', related_name='reports', to='form.thyroidinspectoption', verbose_name='Щитовидная железа'),
        ),
    ]
