# Generated by Django 5.1.12 on 2025-11-23 00:29

from django.db import migrations

INSP_SKIN = {
    "CLN":"чистые, без высыпаний",
    "DRY":"сухость",
    "PAL":"бледность",
    "PIG":"гиперпигментация",
    "JAN":"желтушность",
    "EDM":"отёки",
    "NON":"-",
    }

INSP_LYMP_THYR = {
    "NRM":"не увеличены",
    "PAL":"пальпируются",
    "PNF":"болезненны",
    "PNL":"безболезненны",
    "NON":"-",
    }
    
INSP_MUSC = {
    "NRM":"суставы без деформаций",
    "PAI":"отмечаются боли",
    "LMT":"ограничение движений",
    "EDE":"отёк",
    "NON":"-",
    }

def forwards_func(apps, schema_editor):
    SkinInspectOption = apps.get_model("form", "SkinInspectOption")
    ThyroidInspectOption = apps.get_model("form", "ThyroidInspectOption")
    MuscoskeletalInspectOption = apps.get_model("form", "MuscoskeletalInspectOption")
    Report = apps.get_model("form", "Report")

    code_to_obj_thyr = {}
    code_to_obj_skin = {}
    code_to_obj_musc = {}
    for code, label in INSP_LYMP_THYR.items():
        obj, created = ThyroidInspectOption.objects.get_or_create(
            code=code,
            defaults={"label": label},
        )
        if not created and obj.label != label:
            obj.label = label
            obj.save(update_fields=["label"])
        code_to_obj_thyr[code] = obj
        
    for code, label in INSP_SKIN.items():
        obj, created = SkinInspectOption.objects.get_or_create(
            code=code,
            defaults={"label": label},
        )
        if not created and obj.label != label:
            obj.label = label
            obj.save(update_fields=["label"])
        code_to_obj_skin[code] = obj
        
    for code, label in INSP_MUSC.items():
        obj, created = MuscoskeletalInspectOption.objects.get_or_create(
            code=code,
            defaults={"label": label},
        )
        if not created and obj.label != label:
            obj.label = label
            obj.save(update_fields=["label"])
        code_to_obj_musc[code] = obj

  
    for report in Report.objects.all():
        code = report.insp_Thyroid
        if not code:
            continue
        if code == "NON":
            continue
        opt = code_to_obj_thyr.get(code)
        if opt is not None:
            report.insp_thyroid.add(opt)
            
        code = report.insp_Musculoskeletal
        if not code:
            continue
        if code == "NON":
            continue
        opt = code_to_obj_musc.get(code)
        if opt is not None:
            report.insp_musculoskeletal.add(opt)
            
        code = report.insp_Skin
        if not code:
            continue
        if code == "NON":
            continue
        opt = code_to_obj_skin.get(code)
        if opt is not None:
            report.insp_skin.add(opt)


def backwards_func(apps, schema_editor):
    """
    Обратная миграция: если откатываемся, берём первый элемент из M2M
    и кладём в старое поле insp_Lymph.
    """
    SkinInspectOption = apps.get_model("form", "LymphInspectOption")
    ThyroidInspectOption = apps.get_model("form", "ThyroidInspectOption")
    MuscoskeletalInspectOption = apps.get_model("form", "MuscoskeletalInspectOption")
    Report = apps.get_model("form", "Report")


    for report in Report.objects.all():
        opts = list(report.insp_thyroid.all())
        if opts:
            # берём первый попавшийся код
            report.insp_Thyroid = opts[0].code
        else:
            report.insp_Thyroid = "NON"
            
        
        opts = list(report.insp_skin.all())
        if opts:
            # берём первый попавшийся код
            report.insp_Skin = opts[0].code
        else:
            report.insp_Skin = "NON"
            
        
        opts = list(report.insp_musculoskeletal.all())
        if opts:
            # берём первый попавшийся код
            report.insp_Musculoskeletal = opts[0].code
        else:
            report.insp_Musculoskeletal = "NON"
            
        report.save(update_fields=["insp_Thyroid", "insp_Skin", "insp_Musculoskeletal"])
            
            



class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_muscoskeletalinspectoption_skininspectoption_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
