# Generated by Django 5.1.12 on 2025-11-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_migrate_insp_mus_skin_thyr_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Не указан')], default='U', max_length=2, null=True, verbose_name='Пол'),
        ),
    ]
