# Generated by Django 5.1.12 on 2026-01-13 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_alter_patient_growth_alter_patient_weight_userinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
