# Generated by Django 5.1.12 on 2026-01-14 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('form', '0012_prescription_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('biochem', 'Биохимия'), ('protein', 'Белковый обмен'), ('lipid', 'Липидный профиль'), ('carb', 'Углеводный обмен'), ('iron', 'Железо/ферритин'), ('micro', 'Микроэлементы'), ('inflamm', 'Воспаление'), ('allergy', 'Аллергология'), ('thyroid', 'Щитовидная железа'), ('hemat', 'Гематология'), ('platelet', 'Тромбоциты'), ('leuko', 'Лейкоформула'), ('hormon', 'Гормоны')], max_length=20, verbose_name='Тип анализа')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата анализа')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_entries', to='form.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', '-taken_at'], name='form_labent_patient_4c8d96_idx'), models.Index(fields=['kind', '-taken_at'], name='form_labent_kind_38e520_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
