# Generated by Django 5.1.12 on 2026-01-23 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_labdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergiesinfections',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergies_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='biochemistry',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biochemistry_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='carbohydratemetabolism',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbohydrate_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='hematology',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hematology_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='hormonallevels',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hormonal_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='inflammatorymarkers',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflammatory_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='ironmetabolism',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iron_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='leukocytes',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leukocytes_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='lipidmetabolism',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lipid_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='micronutrients',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micronutrients_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='platelets',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platelets_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='proteinmetabolism',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein_obj', to='form.labentry'),
        ),
        migrations.AddField(
            model_name='thyroidfunction',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thyroid_obj', to='form.labentry'),
        ),
        migrations.AlterField(
            model_name='labdocument',
            name='file',
            field=models.FileField(upload_to='lab_docs/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='labdocument',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Замечания'),
        ),
    ]
