# Generated by Django 5.1.12 on 2026-01-24 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_allergiesinfections_entry_biochemistry_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Воздействие')),
            ],
            options={
                'verbose_name': 'Воздействие',
                'verbose_name_plural': 'Воздействия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['title'], 'verbose_name': 'Препарат', 'verbose_name_plural': 'Препараты'},
        ),
        migrations.AddField(
            model_name='medicine',
            name='usage',
            field=models.TextField(blank=True, default='', verbose_name='Применение'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=200, verbose_name='Доза'),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='make_staff',
            field=models.BooleanField(default=True, verbose_name='Сделать сотрудником'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='form.medicineeffect', verbose_name='Воздействие'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='form.medicinetype', verbose_name='Тип'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('title', 'effect', 'mtype'), name='uniq_medicine_name_effect_type'),
        ),
    ]
