# Generated by Django 5.1.12 on 2026-01-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_medicineeffect_medicinetype_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
    ]
