# Generated by Django 5.1.12 on 2026-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_remove_prescription_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='life_antibiotics',
            field=models.CharField(max_length=200, null=True, verbose_name='Последний приём антибиотиков'),
        ),
        migrations.AddField(
            model_name='report',
            name='life_covid',
            field=models.BooleanField(default=False, verbose_name='COVID-19'),
        ),
        migrations.AddField(
            model_name='report',
            name='life_physAct',
            field=models.CharField(max_length=200, null=True, verbose_name='Физическая активность'),
        ),
        migrations.AddField(
            model_name='report',
            name='life_sleepMode',
            field=models.CharField(max_length=200, null=True, verbose_name='Режим сна'),
        ),
        migrations.AddField(
            model_name='report',
            name='life_stress',
            field=models.CharField(max_length=200, null=True, verbose_name='Наличие стресса'),
        ),
        migrations.AddField(
            model_name='report',
            name='life_vaccinationDate',
            field=models.DateTimeField(null=True, verbose_name='Дата вакцинации'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментариий'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=200, null=True, verbose_name='Длительность'),
        ),
    ]
