# Generated by Django 5.1.12 on 2026-02-07 23:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_report_life_antibiotics_report_life_covid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_diagnosis', models.CharField(max_length=300, verbose_name='Основное заболевание')),
                ('comorbidities', models.CharField(blank=True, max_length=500, verbose_name='Сопутствующие заболевания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_hypotheses', to='form.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Диагностическая гипотеза',
                'verbose_name_plural': 'Диагностические гипотезы',
                'ordering': ['-created_at'],
            },
        ),
    ]
