# Generated by Django 5.1.12 on 2026-02-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_diagnostichypothesis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Нутрицевтическая коррекция', 'verbose_name_plural': 'Нутрицевтические коррекции'},
        ),
        migrations.AddField(
            model_name='report',
            name='comment_diet',
            field=models.CharField(max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='report',
            name='anamnesis',
            field=models.CharField(max_length=1000, verbose_name='Анамнез заболевания'),
        ),
    ]
