# Generated by Django 5.1.12 on 2026-02-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_alter_prescription_options_report_comment_diet_and_more'),
    ]

    operations = [
    ]
