# Generated by Django 5.1.12 on 2026-02-11 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_merge_20260212_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbdomenInspectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Опция осмотра живота',
                'verbose_name_plural': 'Опции осмотра живота',
            },
        ),
        migrations.CreateModel(
            name='HeredityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Наследственное заболевание',
                'verbose_name_plural': 'Наследственные заболевания',
            },
        ),
        migrations.CreateModel(
            name='TongueInspectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Опция осмотра языка',
                'verbose_name_plural': 'Опции осмотра языка',
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='allergic',
        ),
        migrations.AddField(
            model_name='report',
            name='heredity_Other',
            field=models.CharField(blank=True, max_length=100, verbose_name='другое'),
        ),
        migrations.AddField(
            model_name='report',
            name='insp_Limbs',
            field=models.CharField(default='', max_length=150, verbose_name='Стопы, ладони, локти, ногти, волосы:'),
        ),
        migrations.AddField(
            model_name='report',
            name='insp_Muscle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Мышечный тонус'),
        ),
        migrations.AddField(
            model_name='report',
            name='insp_Swelling',
            field=models.CharField(blank=True, max_length=300, verbose_name='Отёки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='diabetes',
            field=models.CharField(choices=[('Y', 'да'), ('N', 'нет'), ('U', 'неизвестно')], max_length=1, verbose_name='Диабет'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insp_Abdomen',
            field=models.CharField(choices=[('SFT', 'мягкий'), ('MTN', 'умеренно напряжённый'), ('TNS', 'напряжённый'), ('BLT', 'вздутие'), ('NPN', 'безболезненный'), ('PNF', 'болезненный'), ('SAV', 'перистальтика сохранена'), ('WEA', 'перистальтика ослаблена'), ('ABS', 'перистальтика отсутствует'), ('NON', '-')], default='NON', max_length=3, verbose_name='Живот'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insp_Skin',
            field=models.CharField(choices=[('CLN', 'чистые, без высыпаний'), ('DRY', 'сухость'), ('PAL', 'бледность'), ('PIG', 'гиперпигментация'), ('JAN', 'желтушность'), ('EDM', 'чёрный акантоз'), ('NON', '-')], default='NON', max_length=3, verbose_name='Кожа и слизистые'),
        ),
        migrations.AddField(
            model_name='report',
            name='insp_abdomen',
            field=models.ManyToManyField(blank=True, help_text='Можно выбрать несколько состояний', related_name='reports', to='form.abdomeninspectoption', verbose_name='Живот'),
        ),
        migrations.AddField(
            model_name='report',
            name='autoimmune_label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoimmune+', to='form.heredityoption'),
        ),
        migrations.AddField(
            model_name='report',
            name='cardiovascular_label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardiovascular+', to='form.heredityoption'),
        ),
        migrations.AddField(
            model_name='report',
            name='diabetes_label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diabetes+', to='form.heredityoption'),
        ),
        migrations.AddField(
            model_name='report',
            name='oncological_label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oncological+', to='form.heredityoption'),
        ),
        migrations.AddField(
            model_name='report',
            name='thyroid_label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thyroid+', to='form.heredityoption'),
        ),
        migrations.AddField(
            model_name='report',
            name='insp_Tongue',
            field=models.ManyToManyField(blank=True, help_text='Можно выбрать несколько состояний', related_name='reports', to='form.tongueinspectoption', verbose_name='Язык'),
        ),
    ]
