# Generated by Django 5.1.12 on 2026-02-13 21:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_skin_tongue_abdome_to m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodplanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Протокол')),
                ('comment', models.TextField(verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Шаблон диетологической рекомендации',
                'verbose_name_plural': 'Шаблоны диетологических рекомендаций',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='autoimmune',
            field=models.CharField(choices=[('U', 'неизвестно'), ('N', 'нет'), ('Y', 'да')], default='U', max_length=1, verbose_name='Аутоиммунные заболевания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cardiovascular',
            field=models.CharField(choices=[('U', 'неизвестно'), ('N', 'нет'), ('Y', 'да')], default='U', max_length=1, verbose_name='Сердечно‑сосудистые заболевания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='diabetes',
            field=models.CharField(choices=[('U', 'неизвестно'), ('N', 'нет'), ('Y', 'да')], default='U', max_length=1, verbose_name='Диабет'),
        ),
        migrations.AlterField(
            model_name='report',
            name='heredity_Other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='report',
            name='oncological',
            field=models.CharField(choices=[('U', 'неизвестно'), ('N', 'нет'), ('Y', 'да')], default='U', max_length=1, verbose_name='Онкологические заболевания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='thyroid',
            field=models.CharField(choices=[('U', 'неизвестно'), ('N', 'нет'), ('Y', 'да')], default='U', max_length=1, verbose_name='Заболевания щитовидной железы'),
        ),
        migrations.CreateModel(
            name='Foodplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Протокол')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.patient')),
            ],
            options={
                'verbose_name': 'Диетологическая рекомендация',
                'verbose_name_plural': 'Диетологические рекомендации',
            },
        ),
    ]
