# Generated by Django 5.1.12 on 2026-02-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_foodplantemplate_alter_report_autoimmune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplantemplate',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
