# Generated by Django 5.1.12 on 2026-03-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_alter_foodplantemplate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='anamnesis',
            field=models.CharField(max_length=2048, verbose_name='Анамнез заболевания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='complaints',
            field=models.CharField(max_length=2048, verbose_name='Жалобы'),
        ),
    ]
