# Generated by Django 5.1.12 on 2026-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0026_alter_report_anamnesis_alter_report_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment_diet',
            field=models.CharField(max_length=2048, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contactAllergy',
            field=models.CharField(max_length=512, verbose_name='Контактная аллергия'),
        ),
        migrations.AlterField(
            model_name='report',
            name='foodAllergy',
            field=models.CharField(max_length=512, verbose_name='Пищевая аллергия'),
        ),
        migrations.AlterField(
            model_name='report',
            name='heredity_Other',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insp_Limbs',
            field=models.CharField(default='', max_length=512, verbose_name='Стопы, ладони, локти, ногти, волосы:'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insp_Muscle',
            field=models.CharField(blank=True, max_length=512, verbose_name='Мышечный тонус'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insp_Swelling',
            field=models.CharField(blank=True, max_length=512, verbose_name='Отёки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='intol_Other',
            field=models.CharField(max_length=512, verbose_name='другое'),
        ),
        migrations.AlterField(
            model_name='report',
            name='life_antibiotics',
            field=models.CharField(max_length=1024, null=True, verbose_name='Последний приём антибиотиков'),
        ),
        migrations.AlterField(
            model_name='report',
            name='life_sleepMode',
            field=models.CharField(max_length=1024, null=True, verbose_name='Режим сна'),
        ),
        migrations.AlterField(
            model_name='report',
            name='life_stress',
            field=models.CharField(max_length=1024, null=True, verbose_name='Наличие стресса'),
        ),
        migrations.AlterField(
            model_name='report',
            name='medicineAllergy',
            field=models.CharField(max_length=512, verbose_name='Медикаментозная аллергия'),
        ),
        migrations.AlterField(
            model_name='report',
            name='noAllergy',
            field=models.CharField(max_length=512, verbose_name='Отсутствие аллергии'),
        ),
        migrations.AlterField(
            model_name='report',
            name='seasonalAllergy',
            field=models.CharField(max_length=512, verbose_name='Сезонная аллергия'),
        ),
    ]
