# Generated by Django 5.1.12 on 2026-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_alter_report_comment_diet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='insp_Other',
            field=models.CharField(default='', max_length=1024, verbose_name='Прочее:'),
        ),
        migrations.AlterField(
            model_name='report',
            name='life_physAct',
            field=models.CharField(max_length=1024, null=True, verbose_name='Физическая активность'),
        ),
    ]
