# Generated by Django 5.1.12 on 2026-03-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_alter_report_insp_other_alter_report_life_physact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='anamnesis',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Анамнез заболевания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment_diet',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='report',
            name='complaints',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contactAllergy',
            field=models.CharField(blank=True, max_length=512, verbose_name='Контактная аллергия'),
        ),
        migrations.AlterField(
            model_name='report',
            name='diabetes',
            field=models.CharField(choices=[('U', 'неизвестно'), ('N', 'нет'), ('Y', 'да')], default='U', max_length=1, null=True, verbose_name='Диабет'),
        ),
        migrations.AlterField(
            model_name='report',
            name='diet',
            field=models.CharField(blank=True, choices=[('MEAT', 'преимущественно мясной'), ('PLANT', 'преимущественно растительный'), ('VEG', 'вегатарианский'), ('LOWCARB', 'низкоуглеводный'), ('KET', 'кетогенный'), ('RAW', 'сыроедение'), ('OTHER', 'другое')], max_length=7, null=True, verbose_name='Тип питания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='foodAllergy',
            field=models.CharField(blank=True, max_length=512, verbose_name='Пищевая аллергия'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insp_Limbs',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Стопы, ладони, локти, ногти, волосы:'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insp_Other',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Прочее:'),
        ),
        migrations.AlterField(
            model_name='report',
            name='intol_Other',
            field=models.CharField(blank=True, max_length=512, verbose_name='другое'),
        ),
        migrations.AlterField(
            model_name='report',
            name='life_antibiotics',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Последний приём антибиотиков'),
        ),
        migrations.AlterField(
            model_name='report',
            name='life_physAct',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Физическая активность'),
        ),
        migrations.AlterField(
            model_name='report',
            name='life_sleepMode',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Режим сна'),
        ),
        migrations.AlterField(
            model_name='report',
            name='life_stress',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наличие стресса'),
        ),
        migrations.AlterField(
            model_name='report',
            name='life_vaccinationDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата вакцинации'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mealscount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество приёмов пищи в день'),
        ),
        migrations.AlterField(
            model_name='report',
            name='medicineAllergy',
            field=models.CharField(blank=True, max_length=512, verbose_name='Медикаментозная аллергия'),
        ),
        migrations.AlterField(
            model_name='report',
            name='noAllergy',
            field=models.CharField(blank=True, max_length=512, verbose_name='Отсутствие аллергии'),
        ),
        migrations.AlterField(
            model_name='report',
            name='seasonalAllergy',
            field=models.CharField(blank=True, max_length=512, verbose_name='Сезонная аллергия'),
        ),
        migrations.AlterField(
            model_name='report',
            name='snacks',
            field=models.CharField(blank=True, choices=[('N', 'нет'), ('R', 'редко'), ('O', 'несколько раз в день')], max_length=1, verbose_name='Перекусы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
