# Generated by Django 5.1.12 on 2026-03-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_alter_report_anamnesis_alter_report_comment_diet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='life_vaccinationDate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата вакцинации'),
        ),
        migrations.AlterField(
            model_name='report',
            name='next_date',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Следующий приём'),
        ),
    ]
